apiVersion: v1
kind: Secret
metadata:
    name: msc-dos-svc-secret
    namespace: csc
type: Opaque
data:
    MSC-SECRETS-PASSWORD: ENC[AES256_GCM,data:enrbjJP/JCw=,iv:ERbF8PvqYAPLyT+gaEcr/i7ZK7h7oWPQDMX7TGjoiY4=,tag:eEEtLVAHiPGBmNGY2M9ksg==,type:str]
    TRUST-STORE-PASSWORD: ENC[AES256_GCM,data:s+Z0S12qaaA=,iv:B/bLWhTzSrykF4IN4psHXOj3/z7SuoaANilaeZJNRWo=,tag:InwFky7Xy79nMP59GupBXg==,type:str]
    TNT-API-KEY: ENC[AES256_GCM,data:axoaxSLY8eQ=,iv:jvA31wOnSgihRPW+isWcFwpeEmll61sO9sR/TRT6JQ8=,tag:buoDzQcpe3MRJXZyhmJ85A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://dweumsckv.vault.azure.net
          name: sops-key
          version: d0d64ce0577444ad9f85c2abf21c3eda
          created_at: "2022-04-13T08:33:19Z"
          enc: Jn195wljiw9Wzi2NIVcKF8nflVfEsfLEUg23XdODjMF9bhAomMfV2sHlAjn9vdk7MKINRqz-MeXUpB_omvtTMsQyqr9Gosn9TsNuy3w8ctuNSa6Ir_7UsaOtJuz4TxQGN_X6wOyMrr15I4nvhgHNC-5gLZ6wdARcBaggurtl9cPCTMlAU4gxus2om9fKwfuEm7BLDDFgtIdqO1nEpFaIhi16XjFuSRjApLFzbyfxG5sng9aq-mQVAWmylW8zzi1L2oS1kjVtBkbrWLFqw3gF5C5nzz9ZDIVeBjLnRkGjV-Cg5_ghYp5L8CAoG98DLZcniEiLyd60O8PvZDTM98wORpGev6EsoMSaqXCSprKoA1poCqfGiAUQ_aICsYlfSZtIQPUhN_FcIsvXsaSfJ8VOSYrdfi-xr1hRNJ9gVT1IrAKE1VTQgz2_JJbJ-KnWcMIiobwVJa8EzEAjkmgyBQ64heIsrEH24jpp6reV_HLG6WJj9nHhjlveLfTzInqdRgTozO2XwQAIL7k2EtSH__9Am5u02KQuwnAroyjJ3XGWcNfRU7IIdWQuIn0KEWZedRREMOoYd-Us93VsRVdYcJK7T2yondoOALTjRwQRahxi3Qd5At5XueKDdYn7XXT8jnbHS4DARLrzrhRTnyFYWYmMgeNF_I28UNUvXa69cvafxuo
    hc_vault: []
    age: []
    lastmodified: "2022-04-13T08:33:20Z"
    mac: ENC[AES256_GCM,data:AG1DsiHwkPeh5GKgJDrE3nNiYECUu7+EHk1Gu8EviGeu7xvYOLUD3rV4eraHKe+2f0OqrB53jsjAYIdA8Qwg1fdX7RCfws7XwRMZj2Z60iSqbfGhUi1ezEF79ZQptIRnVfy7rgDOkkqKjlkx7bhJza8+/e3KZBDAkQQNaZV03qQ=,iv:oUmAxZt5HmMU1YRXhOIa8g9l76ztbfhF9HZTyfuTs1E=,tag:jgpdbvDiccTHcu5jGbF0lA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
