apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-kustomize/app
    plugin:
      name: kustomized-helm
    repoURL: https://github.com/akanthos/deployment-examples.git
    targetRevision: HEAD