apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../base
patchesStrategicMerge:
  - argocd-repo-server-patch.yaml
  - argocd-configmap-knownhosts-patch.yaml
  - argocd-configmap-patch.yaml
  - argocd-server-patch.yaml