apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: csc
resources:
  - ../../helm_base
  - namespace.yaml
  - secret-generator.yaml

#images:
#  - name: blah-blah:blah
#    newName: alexwhen/docker-2048
#    newTag: latest

#patchesJson6902:
#  - target:
#      group: apps
#      version: v1
#      kind: Deployment
#      name: deployment
#    path: patch/deployment_patch.yml